variable "cluster-name" {}
variable "cidr_block" {}
variable "vpc-name" {}
variable "env" {}
variable "igw-name" {}
variable "pub-subnet-count" {}
variable "pub-cidr-block" {}
variable "pub-availability-zone" {}
variable "pub-sub-name" {}
variable "pri-subnet-count" {}
variable "pri-cidr-block" {}
variable "pri-availability-zone" {}
variable "pri-sub-name" {}
variable "public-rt-name" {}
variable "eip-name" {}
variable "ngw-name" {}
variable "private-rt-name" {}
variable "eks-sg" {}

